version: 2.1

jobs:
  "Classic":
    docker:
      - image: "cimg/base:2022.03"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'sudo apt-get update && sudo apt-get install -y && sudo rm -rf /var/lib/apt/lists/*'
#      - run:
#          name: Installing GCC
#          command: 'sudo apt-get update && sudo apt-get install -y gcc-9 g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install deps
          command: |
            sudo apt-get update && sudo apt-get install -y zlib1g-dev
            sudo apt-get update && sudo apt-get install -y libssl-dev
            sudo apt-get update && sudo apt-get install -y libpcre3-dev
            sudo apt-get update && sudo apt-get install -y libbz2-dev
            sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
            sudo apt-get update && sudo apt-get install -y libmysql++-dev
      - run:
          name: Check versions
          command: |
            gcc --version
            cmake --version
      - run:
          name: Build Classic
          command: |
            mkdir ascemu_classic
            cd ascemu_classic
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=Classic
            cd ..
            cd ascemu_classic
            make -j 4
            cd ..

            
workflows:
  version: 2.1
  build:
    jobs:
      - "Classic"

